### ISSUE TITLE
Up-to-date User Guide for Android

### ISSUE THREAD

**Issue by zs6buj** [mavlink/qgc-user-guide#126]
Sorry but I've looked everywhere and can't find a more up-to-date user guide than this one:

https://docs.qgroundcontrol.com/en/

If there is later Android user guide information, please give me a hint as to where to find it. 

I'm been trying the Android build on Google Play, and also the daily test build, but finding information is proving very difficult. The Android control interface has changed a lot since I first used it, and it seems not all actions are activated until the craft is armed and (sometimes) airborne. It's not ideal figuring this out while the craft is flying, no? 

Thanks in advance for any help. If I'm in the wrong forum, please just show me where I can raise this.

**Comment by DonLakeFlyer** [comment]
There are no docs which are specific to an OS or device. The QGC ui is mainly the same across all versions and the docs you pointed to are the only ones. If you have usage question please use the various support links as shown here: http://qgroundcontrol.com/#resources. And we can hopefully help you out.
