### ISSUE TITLE
document the mavlink console

### ISSUE THREAD

**Issue by bkueng** [mavlink/qgc-user-guide#143]
I often need to point people to the mavlink console, so it would be good to have instructions and a screenshot showing how to access it.

I see that all Items on https://docs.qgroundcontrol.com/en/toolbar/toolbar.html have a separate page already except for the Analyze tab.

**Comment by hamishwillee** [comment]
Yes. There is actually a broader requirement to go through and integrate all the changes that were added in [3.2](https://docs.qgroundcontrol.com/en/releases/stable_v3.2_long.html). Don needs help with that, but has not previously been a priority. I hope to find time in coming months, management permitting.

**Comment by DonLakeFlyer** [comment]
And now 3.3 as well which will be going out the door soon.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mavlink/qgc-user-guide/pull/145
