### ISSUE TITLE
Altitude information missing on QGC

### ISSUE THREAD

**Issue by Pauloledes** [mavlink/qgc-user-guide#144]
Hi, I am currently using Intel Aero Drone with Pixhawk and PX4 with the help of QGroundControl.
I connected the drone to my computer and I am able to see through the drone's camera via QGC.
I also have access to the 3 angles of the drone in live that are the heading, the pitch and the roll. Unfortunately, the place where I should be reading the altitude is left blank and I can not figure out why. I have taken a screenshot of what it looks like, I previously realised calibration of the sensors.
Thanks for your help,
Best regards,
Paul. #
![parameters qgc](https://user-images.githubusercontent.com/40398982/42468921-35bb9dca-8384-11e8-8d6b-1acbf5ef71f0.png)

**Comment by Pauloledes** [comment]
I have also another problem, maybe they are linked. When I tried to setup a flight mission for the drone, I can not upload it to the drone so it can follow the path. I do not know where the problem comes from because the error message is not really explicit as you can see below... I have do the calibration well though.
![error](https://user-images.githubusercontent.com/40398982/42472542-a36627c2-838f-11e8-9fae-869be6a023ac.png)

**Comment by hamishwillee** [comment]
@Pauloledes This area is for docs issues. Can you please repost in a support channel: https://docs.qgroundcontrol.com/en/Support/Support.html
