### ISSUE TITLE
Broken links in the Survey (Plan Pattern) page

### ISSUE THREAD

**Issue by IeiuniumLux** [mavlink/qgc-user-guide#163]
There are several broken links in [the Survey (Plan Pattern) page](https://github.com/mavlink/qgc-user-guide/blob/9b01f08223df6fa756e883e47f957a069e338ca4/en/PlanView/pattern_survey.md).

https://docs.qgroundcontrol.com/en/PlanView/pattern_survey.html

**Comment by hamishwillee** [comment]
Thanks @IeiuniumLux - much appreciated. The images worked locally due to Windows ignoring file path case, but not on live system or github. I fixed all broken links in the English version. Note that there will be broken links in the Korean version, but these will be fixed up post-re-translation.
