### ISSUE TITLE
Ubuntu dependencies: documentation mentions github readme, but github readme does not contain these dependencies

### ISSUE THREAD

**Issue by thomasgubler** [mavlink/qgc-user-guide#184]
Under https://docs.qgroundcontrol.com/en/getting_started/download_and_install.html under Ubuntu Linux / Compressed Archive it is mentioned to "Install additional packages as specified in the github README. You do not need to install Qt."

However the github README has been stripped of mentioning these dependencies.

**Comment by hamishwillee** [comment]
@DonLakeFlyer Do we still supply the compressed archive? If so, can you let me know what additional packages are required to use it on Ubuntu?

**Comment by DonLakeFlyer** [comment]
> Do we still supply the compressed archive?

Not really. Only AppImage is fully supported.

**Comment by hamishwillee** [comment]
>> Do we still supply the compressed archive?

> Not really. Only AppImage is fully supported.

@DonLakeFlyer So do I remove it then? I saw a post recently where someone was using it with GStreamer, so I am worried perhaps it is "needed".

If we are not deleting we need to supply the dependencies - can you do that?

**Comment by DonLakeFlyer** [comment]
> So do I remove it then?

Remove it.

**Comment by hamishwillee** [comment]
Thanks. Done #189
