### ISSUE TITLE
Stale footer on main page

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgc-user-guide#210]
The 'news' and the copyright are stale:
![Screenshot from 2019-04-19 10-35-54](https://user-images.githubusercontent.com/8315108/56428925-1b565980-628f-11e9-8cb6-f6c36ee96afb.png)
![Screenshot from 2019-04-19 10-36-10](https://user-images.githubusercontent.com/8315108/56428926-1d201d00-628f-11e9-86b1-817ad2c17184.png)

**Comment by hamishwillee** [comment]
Thanks @jaxxzer 

@mrpollo @DonLakeFlyer I have updated the footer copyright to 2019 - I'd have done a range, but not sure of the right ones for Dronecode and QGC.

However not sure how you want to deal with the news section? Remove it altogether somehow or do you want to add blog announcements here for new releases so this is up to date?

**Comment by DonLakeFlyer** [comment]
Remove seems fine to me.

**Comment by hamishwillee** [comment]
OK. Removed. I think this is now done.

**Comment by mrpollo** [comment]
Thanks @hamishwillee @DonLakeFlyer
