### ISSUE TITLE
Daily Build pattern preset change didn't build correctly

### ISSUE THREAD

**Issue by DonLakeFlyer** [mavlink/qgc-user-guide#214]
The link in the daily build feature page links to the .md file. Also the .html file didn't seem to get built.

**Comment by hamishwillee** [comment]
HTML doesn't get generated if a file isn't referenced by the SUMMARY.md.

Fixed by https://github.com/mavlink/qgc-user-guide/commit/49d419df874ad9ab2707aa194d235937c6e1972c

BUT, please check it is where you want it in the sidebar TOC!

**Comment by DonLakeFlyer** [comment]
Ah, I had no idea!
