### ISSUE TITLE
YOUR VEHICLE IS NOT RESPONDING

### ISSUE THREAD

**Issue by sampathkumarch** [mavlink/qgc-user-guide#216]
YOUR VEHICLE IS NOT RESPONDING .

**Comment by hamishwillee** [comment]
This area is for reports of defects in the docs. This document explains where you should ask for help: https://docs.qgroundcontrol.com/en/Support/Support.html

What you need to do is post a request explaining exactly what flight stack and version of QGC you are using, what the vehicle is, how you are attached to QGC, what you were doing before this message etc etc. 

No one can help you with this level of information.
