### ISSUE TITLE
Doc Bug: Fly View : Control Mission: embedded "stop" link broken (others work)

### ISSUE THREAD

**Issue by GitHubrist** [mavlink/qgc-user-guide#221]
Reference: 
https://docs.qgroundcontrol.com/en/FlyView/FlyView.html

Under the Fly View section, 
* Control missions: start, continue, pause, stop and resume.

The hyperlinked word "stop" does not take the reader to an associated section. I am hoping to learn how to "abort" a mission without "E-stop" or "RTL."

Further searching for the word "stop" does not bring up information about stopping a mission, other than with "emergency stop."

I am a 1-day-old QGC user, who has flown two successful 6-waypoint missions, over my house, taking off and RTL from a tree-lined backyard.  I still have a drone. All credit to QGC developers. Thank you.

**Comment by hamishwillee** [comment]
I have fixed the link by removing it. From fly view you can start, pause, resume and continue. 

To answer your question though there is no particular abort or stop command. The pause is the same thing. You might also do land to stop the mission, and once you've paused you can guide the vehicle to land via the GCS or your RC control.
