### ISSUE TITLE
"Flight Modes" section is empty

### ISSUE THREAD

**Issue by gmgremillion** [mavlink/qgc-user-guide#28]
"Flight Modes" section needs to be populated.

I'm specifically interested in flight mode needed for local position control with the PX4FLOW. "Loiter" mode does not exist in the current version of QGC.

**Comment by DonLakeFlyer** [comment]
I believe it's called "Hold" instead of "Loiter"

**Comment by DonLakeFlyer** [comment]
ArduPilot side is done

**Comment by hamishwillee** [comment]
Fixed by https://github.com/mavlink/qgc-user-guide/pull/88
