### ISSUE TITLE
QGroundControl is displaying full-screen and cannot be changed back to windowed mode

### ISSUE THREAD

**Issue by rdarnold** [mavlink/qgc-user-guide#291]
Using QGroundControl on Ubuntu 16.04 LTS.  I have been using QGroundControl v3.5.3 for months without issue.   I opened up QGroundControl v3.4.1 by mistake (I have icons for both side-by-side on my desktop).  It opened in a weird "full full screen" mode covering up the entire screen including the taskbar, the system menu, etc., and did not have a system menu.  The very top of the screen was QGC's "File" option.  The only way to exit was to use "File->Exit."  I then tried opening up v3.5.3 and it, too, is now showing in the same weird full screen mode.  I cannot get it to go back to a windowed or even a "standard" full screen mode.  I have tried deleting QGroundControl.ini, ALT-Space, ALT-F7, ALT-F8, but none of these work.  I cannot move the window at all.  I cannot resize it, and I don't see any options controlling these in Settings. I have been searching on Google for more than 2 hours and I can't find a solution.  What the hell is up with this thing?

**Comment by DonLakeFlyer** [comment]
Other than deleting the .ini there isn't much else to do. Could possibly be some strange OS thing going on. Hard to say since the version you are running are ancient.
