### ISSUE TITLE
QGCS sending too many request to change FLIGHT MODE

### ISSUE THREAD

**Issue by vtol-ronit** [mavlink/qgc-user-guide#301]
Hi everyone,

I'm developing a custom autopilot using mavlink version 2 and communicating with QGCS verison 4.0 in ubuntu 20.04.

The flow is I'm giving a takeoff command at disARM condition from QGCS and autopilot will takeoff in guided mode. Everything is fine till here. But when I'm sending it to the AUTO_MODE, since autopilot has no mission it rejects this command and sends a status text message (with MAV_SEVERITY_ERROR) . QGCS also shows this perfectly.

But problem is sometime QGCS sends too many request continuously around 1000+ times for AUTO mode. And this happens  sometime not all the time. So I wanted to know why this is happening?

I'm adding the QGCS CONSOLE log file, it might helpful anyway I don't understand.
[auto_bug.txt](https://github.com/mavlink/qgc-user-guide/files/7431999/auto_bug.txt)

**Comment by hamishwillee** [comment]
@vtol-ronit If you can reproduce on standard QGC we can help, but otherwise no dev team generally has time to support arbitrary code variations.

**Comment by vtol-ronit** [comment]
sorry for the very late reply. But that was the issue with circular buffer that I was using.
