### ISSUE TITLE
Guide needs info about how to "get a Slack signin and the add then connect to the channel"

### ISSUE THREAD

**Issue by aib** [mavlink/qgc-user-guide#312]
As discussed in #311.

Searching around only leads to more people confused by how to do this:

https://discuss.px4.io/t/slack-invites/22857
https://discuss.px4.io/t/qgc-slack-error/23188

Slack itself is no help and implies it's not possible:

![screenshot_20211215_140512](https://user-images.githubusercontent.com/154400/146175605-a5498df0-f8fc-4e40-8d6d-1a96a0b2fd1e.png)

**Comment by hamishwillee** [comment]
Let me just check what you have tried - have you clicked http://slack.px4.io/ ?
That takes me to a place where I can get an invite:
![image](https://user-images.githubusercontent.com/5368500/146280041-2b49e146-7efa-40a0-9fb0-c65c79f42992.png)

If that works we could update https://docs.qgroundcontrol.com/master/en/Support/Support.html#developer_chat like this:
![image](https://user-images.githubusercontent.com/5368500/146280161-20476305-6aae-47ec-8424-0af04be353b8.png)

**Comment by aib** [comment]
Ah, that was precisely the information I was missing. Thanks, it indeed works.

**Comment by hamishwillee** [comment]
Thanks - also for posting the fix!
