### ISSUE TITLE
Troubleshooting subpage not being fuctional (translation issues?)

### ISSUE THREAD

**Issue by junwoo091400** [mavlink/qgc-user-guide#334]
## Context
From the PR #329, I have created & moved the sub pages under the Troubleshooting folder. And it seems that it broke the doc link in other languages (korean), in regards to:
1. The sub-folder structure on the left panel isn't correct / updated as in the english page
2. The links lead to the "*.md" files, not the ".html" page. So the click on the '[Connection problems](https://docs.qgroundcontrol.com/master/ko/troubleshooting/vehicle_connection.md)' doesn't work at all (webpage stays the same)

### Korean Page
![image](https://user-images.githubusercontent.com/23277211/167868635-da4041af-5efd-41a3-b5a1-374cf5d7033d.png)
https://docs.qgroundcontrol.com/master/ko/troubleshooting/qgc_usage.html

### English Page
![image](https://user-images.githubusercontent.com/23277211/167868569-f51a5b98-1f28-4d75-abd8-f733297bc49e.png)
https://docs.qgroundcontrol.com/master/en/troubleshooting/qgc_usage.html

## Analysis
This is caused by the wrong translation of the SUMMARY.md. Which probably went through the Crowd-in updates. Any thoughts on why this happens? @hamishwillee 
- Korean : https://github.com/mavlink/qgc-user-guide/blob/master/ko/SUMMARY.md
- English : https://github.com/mavlink/qgc-user-guide/blob/master/en/SUMMARY.md

**Comment by hamishwillee** [comment]
All fixed. The sidebar had all sorts of odd formatting - crowdin couldn't parse the layout properly.
