### ISSUE TITLE
Windows Daily  not working

### ISSUE THREAD

**Issue by zenetio** [mavlink/qgc-user-guide#48]
The daily HEAD:6b10539a5 2017-03-09 11:28:25 is not working on my machine. It does not connect. I verified that this version has about 90k while the last one, 3.1.3, has about 140k. Not sure if something missing. I had to revert to 3.1.3
I am using Windows 10

**Comment by DonLakeFlyer** [comment]
Can you move this to here: https://github.com/mavlink/qgroundcontrol/issues. And also provide some details on what/how your are trying to connect?
